export interface LibraryGame {
  id: string;
  title: string;
  subject: 'Math' | 'Reading' | 'Science' | 'Social Studies';
  gradeLevel: 'K-2' | '3-5';
  topic: string;
  description: string;
  gameType: 'platformer' | 'runner' | 'puzzle' | 'quiz';
  difficulty: 'easy' | 'medium' | 'hard';
  icon: string; // Emoji
  backgroundColor: string;
  accentColor: string;
}

export const LIBRARY_GAMES: LibraryGame[] = [
  // MATH (K-2)
  {
    id: 'counting-clouds',
    title: 'Counting Clouds',
    subject: 'Math',
    gradeLevel: 'K-2',
    topic: 'Number Recognition',
    description: 'Count fluffy clouds floating by! Perfect for learning numbers 1-10.',
    gameType: 'quiz',
    difficulty: 'easy',
    icon: '☁️',
    backgroundColor: 'bg-gradient-to-br from-sky-100 to-blue-200',
    accentColor: 'bg-blue-500',
  },
  {
    id: 'addition-adventure',
    title: 'Addition Adventure',
    subject: 'Math',
    gradeLevel: 'K-2',
    topic: 'Basic Addition',
    description: 'Solve simple addition problems (1+1 to 5+5) to collect treasure!',
    gameType: 'platformer',
    difficulty: 'easy',
    icon: '➕',
    backgroundColor: 'bg-gradient-to-br from-green-100 to-emerald-200',
    accentColor: 'bg-emerald-500',
  },
  {
    id: 'shape-sorter',
    title: 'Shape Sorter',
    subject: 'Math',
    gradeLevel: 'K-2',
    topic: 'Geometry Basics',
    description: 'Identify circles, squares, triangles, and more! Learn shapes through sorting.',
    gameType: 'puzzle',
    difficulty: 'easy',
    icon: '🔷',
    backgroundColor: 'bg-gradient-to-br from-purple-100 to-violet-200',
    accentColor: 'bg-violet-500',
  },
  // MATH (3-5)
  {
    id: 'multiplication-mountain',
    title: 'Multiplication Mountain',
    subject: 'Math',
    gradeLevel: '3-5',
    topic: 'Multiplication',
    description: 'Climb to the top by solving times tables 1-5! Build fluency and speed.',
    gameType: 'runner',
    difficulty: 'medium',
    icon: '✖️',
    backgroundColor: 'bg-gradient-to-br from-amber-100 to-orange-200',
    accentColor: 'bg-orange-500',
  },
  {
    id: 'fraction-quest',
    title: 'Fraction Quest',
    subject: 'Math',
    gradeLevel: '3-5',
    topic: 'Fractions',
    description: 'Visualize and compare fractions (1/2, 1/4, 1/3) through pizza slices!',
    gameType: 'puzzle',
    difficulty: 'medium',
    icon: '🍕',
    backgroundColor: 'bg-gradient-to-br from-red-100 to-rose-200',
    accentColor: 'bg-rose-500',
  },
  {
    id: 'division-dash',
    title: 'Division Dash',
    subject: 'Math',
    gradeLevel: '3-5',
    topic: 'Division',
    description: 'Race through division problems! Master basic division facts.',
    gameType: 'runner',
    difficulty: 'medium',
    icon: '➗',
    backgroundColor: 'bg-gradient-to-br from-teal-100 to-cyan-200',
    accentColor: 'bg-cyan-500',
  },
  // READING (K-2)
  {
    id: 'alphabet-runner',
    title: 'Alphabet Runner',
    subject: 'Reading',
    gradeLevel: 'K-2',
    topic: 'Letter Recognition',
    description: 'Collect letters A-Z in order! Perfect for alphabet practice.',
    gameType: 'runner',
    difficulty: 'easy',
    icon: '🔤',
    backgroundColor: 'bg-gradient-to-br from-pink-100 to-rose-200',
    accentColor: 'bg-pink-500',
  },
  {
    id: 'phonics-jump',
    title: 'Phonics Jump',
    subject: 'Reading',
    gradeLevel: 'K-2',
    topic: 'Phonics',
    description: 'Jump on words that start with the right sound! Learn beginning phonics.',
    gameType: 'platformer',
    difficulty: 'easy',
    icon: '🎵',
    backgroundColor: 'bg-gradient-to-br from-yellow-100 to-amber-200',
    accentColor: 'bg-amber-500',
  },
  {
    id: 'sight-word-chase',
    title: 'Sight Word Chase',
    subject: 'Reading',
    gradeLevel: 'K-2',
    topic: 'Sight Words',
    description: 'Catch common sight words (the, and, is, it)! Build reading fluency.',
    gameType: 'runner',
    difficulty: 'easy',
    icon: '👁️',
    backgroundColor: 'bg-gradient-to-br from-indigo-100 to-blue-200',
    accentColor: 'bg-indigo-500',
  },
  // READING (3-5)
  {
    id: 'spelling-adventure',
    title: 'Spelling Adventure',
    subject: 'Reading',
    gradeLevel: '3-5',
    topic: 'Spelling',
    description: 'Spell grade-level words correctly to unlock treasure chests!',
    gameType: 'quiz',
    difficulty: 'medium',
    icon: '✏️',
    backgroundColor: 'bg-gradient-to-br from-lime-100 to-green-200',
    accentColor: 'bg-lime-500',
  },
  {
    id: 'vocabulary-valley',
    title: 'Vocabulary Valley',
    subject: 'Reading',
    gradeLevel: '3-5',
    topic: 'Vocabulary',
    description: 'Use context clues to find word meanings! Expand your vocabulary.',
    gameType: 'puzzle',
    difficulty: 'medium',
    icon: '📚',
    backgroundColor: 'bg-gradient-to-br from-fuchsia-100 to-purple-200',
    accentColor: 'bg-fuchsia-500',
  },
  {
    id: 'comprehension-quest',
    title: 'Reading Comprehension Quest',
    subject: 'Reading',
    gradeLevel: '3-5',
    topic: 'Reading Comprehension',
    description: 'Read short passages and answer questions! Improve understanding.',
    gameType: 'quiz',
    difficulty: 'medium',
    icon: '📖',
    backgroundColor: 'bg-gradient-to-br from-orange-100 to-red-200',
    accentColor: 'bg-orange-600',
  },
  // SCIENCE (K-2)
  {
    id: 'weather-watcher',
    title: 'Weather Watcher',
    subject: 'Science',
    gradeLevel: 'K-2',
    topic: 'Weather',
    description: 'Match weather types (sunny, rainy, snowy)! Learn about weather patterns.',
    gameType: 'puzzle',
    difficulty: 'easy',
    icon: '🌦️',
    backgroundColor: 'bg-gradient-to-br from-sky-100 to-cyan-200',
    accentColor: 'bg-sky-500',
  },
  {
    id: 'animal-match',
    title: 'Animal Match',
    subject: 'Science',
    gradeLevel: 'K-2',
    topic: 'Animal Classification',
    description: 'Sort animals into groups: mammals, birds, fish, and reptiles!',
    gameType: 'puzzle',
    difficulty: 'easy',
    icon: '🐾',
    backgroundColor: 'bg-gradient-to-br from-green-100 to-lime-200',
    accentColor: 'bg-green-500',
  },
  {
    id: 'plant-parts',
    title: 'Plant Parts',
    subject: 'Science',
    gradeLevel: 'K-2',
    topic: 'Plant Biology',
    description: 'Label roots, stems, leaves, and flowers! Learn plant anatomy.',
    gameType: 'quiz',
    difficulty: 'easy',
    icon: '🌱',
    backgroundColor: 'bg-gradient-to-br from-emerald-100 to-green-200',
    accentColor: 'bg-emerald-600',
  },
  // SCIENCE (3-5)
  {
    id: 'solar-system',
    title: 'Solar System Explorer',
    subject: 'Science',
    gradeLevel: '3-5',
    topic: 'Space Science',
    description: 'Learn the order of planets from the Sun! Explore our solar system.',
    gameType: 'quiz',
    difficulty: 'medium',
    icon: '🪐',
    backgroundColor: 'bg-gradient-to-br from-purple-100 to-indigo-200',
    accentColor: 'bg-purple-600',
  },
  {
    id: 'matter-matters',
    title: 'Matter Matters',
    subject: 'Science',
    gradeLevel: '3-5',
    topic: 'States of Matter',
    description: 'Classify objects as solid, liquid, or gas! Understand matter.',
    gameType: 'puzzle',
    difficulty: 'medium',
    icon: '💧',
    backgroundColor: 'bg-gradient-to-br from-blue-100 to-teal-200',
    accentColor: 'bg-blue-600',
  },
  {
    id: 'simple-machines',
    title: 'Simple Machines',
    subject: 'Science',
    gradeLevel: '3-5',
    topic: 'Physics',
    description: 'Identify levers, pulleys, wedges, and more! Learn about simple machines.',
    gameType: 'quiz',
    difficulty: 'medium',
    icon: '⚙️',
    backgroundColor: 'bg-gradient-to-br from-gray-100 to-slate-200',
    accentColor: 'bg-slate-600',
  },
  // SOCIAL STUDIES (K-5)
  {
    id: 'us-states-race',
    title: 'US States Race',
    subject: 'Social Studies',
    gradeLevel: '3-5',
    topic: 'Geography',
    description: 'Identify and place US states on the map! Learn geography.',
    gameType: 'quiz',
    difficulty: 'medium',
    icon: '🗺️',
    backgroundColor: 'bg-gradient-to-br from-red-100 to-blue-200',
    accentColor: 'bg-blue-700',
  },
  {
    id: 'community-helpers',
    title: 'Community Helpers',
    subject: 'Social Studies',
    gradeLevel: 'K-2',
    topic: 'Community',
    description: 'Match jobs to community helpers (firefighter, doctor, teacher)!',
    gameType: 'puzzle',
    difficulty: 'easy',
    icon: '👷',
    backgroundColor: 'bg-gradient-to-br from-yellow-100 to-orange-200',
    accentColor: 'bg-yellow-600',
  },
];
